### ISSUE TITLE
Memory allocation (in dependencies)

### ISSUE THREAD

**Issue by ZuseZ4** [wsmoses/Enzyme.jl#159]
I've just been looking into the Julia side for some inspiration and stumbled onto this comment:
https://github.com/wsmoses/Enzyme.jl/blob/790ab6e31e50847f2dea7d357f89d72fe887d81f/src/Enzyme.jl#L126

> 
* `f` may not allocate memory, this restriction is likely to be removed in
  future versions. Technically it can currently allocate memory directly, but not in a function called by `f`.
  
  Is this one still up to date? I can't remember to have seen this note on the C API docs, so I was wondering.

**Comment by wsmoses** [comment]
That issue is specific to Julia's Garbage collection, rather than the Enzyme API do I don't imagine it would be a problem for Rust.

**Comment by ZuseZ4** [comment]
Makes sense, then I will close this.  Thanks!
