### ISSUE TITLE
Enzyme autodiff breaking on tanh function

### ISSUE THREAD

**Issue by sandreza** [wsmoses/Enzyme.jl#37]
The following example crashes Julia on my system

```julia
using Enzyme
autodiff(tanh, Active(1.0))
```

version info of my system:
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
OS: macOS (x86_64-apple-darwin18.7.0)
CPU: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
WORD_SIZE: 64
LIBM: libopenlibm
LLVM: libLLVM-9.0.1 (ORCJIT, skylake)

**Comment by wsmoses** [comment]
There's two solutions to this -- one more of a long term fix, and one to immediately resolve this. We should just mark tanh to be lowered to the standard math tanh which is perfectly fine (and we'll add this immediately).

As a broader question, the way this is currently running it's trying to differentiate Julia's custom definition of the tanh function, which calls a function without definition `jl_f_tuple`, which we should add a custom adjoint for from the Julia lowering side. Related to this, it appears the function requires function pointers that have already been lowered to integers known to the runtime -- which we should enable JIT re-entrance to retrieve. @vchuravy
