### ISSUE TITLE
libLLVM-11jl.so: cannot open shared object file

### ISSUE THREAD

**Issue by seadra** [wsmoses/Enzyme.jl#69]
On Arch Linux, the following problem in Enzyme breaks DiffEqSensitivity, DiffEqFlux, NeuralPDE...

```
ERROR: LoadError: LoadError: InitError: could not load library "/home/seadra/.julia/artifacts/106bae7ef747d3f252feb096f357f676565fcde0/lib/libEnzyme-11.so"
libLLVM-11jl.so: cannot open shared object file: No such file or directory
```

Arch Linux uses llvm 12.0.0

**Comment by vchuravy** [comment]
Please use the Julia binaries from https://julialang.org or the AUR julia-bin. The LLVM and Julia versions are tightly coupled and Arch defaulting to LLVM12 is not advisable. Julia 1.6 has been developed and tested only with LLVM 11

**Comment by seadra** [comment]
Julia works fine with LLVM 12 though. Everything actually worked well before DiffEqFlux switched to Enzyme, so this appears to be an Enzyme issue.

**Comment by seadra** [comment]
Julia works fine with LLVM 12 though. Everything actually worked well before DiffEqFlux switched to Enzyme.jl. This is an Enzyme.jl packaging issue which comes with a dynamically linked libraries specifically referencing to libLLVM-11jl.so.

I successfully compiled Enzyme on my system with LLVM 12. I'm not aware of any blockers that truly prevents using Enzyme with LLVM 12.

**Comment by wsmoses** [comment]
Since it seems that the issue is a broader LLVM in Julia question being worked out in the attached issue, I'm going to close for now.
